console.log("Request and Response")
console.log("HTTP - Hyper Text Transfer Protocol")
console.log("headers - contains additional information in Response")
console.log("Get request - used to retrieve data")
console.log("post request - used to send specific data")
console.log("delete request - used to delete data")
console.log("patch request - used to update data")
console.log("=> Response status code")
console.log("100-199 => informational response")
console.log("200-299 => successful response")
console.log("300-399 => Redirection message")
console.log("400-499 => client error response")
console.log("500-599 => server error")